### ISSUE TITLE
[Docs] The crop stride in paper and code

### ISSUE THREAD

**Issue by promefire** [shaunyuan22/SODA-mmdetection#10]
### Branch

master branch  https://mmdetection.readthedocs.io/en/latest/

### 📚 The doc issue

In the paper ,I see "Directly feeding the high-resolution images in SODA to deep model is infeasible due to the GPU memory limitation,hence we crop original images into a series of 800 × 800
patches with a stride of 650"
But in [tools/img_split](https://github.com/shaunyuan22/SODA-mmdetection/tree/master/tools/img_split)  the stride is 150
so ,which one should i choose

**Comment by shaunyuan22** [comment]
just run the script by default then you get the patches with a stride of 650. 
in `/tools/img_split/sodad_split.py`, the argument `stepSz` is NOT the stride which follows the equation: patch_size - stepSz = stride.
