### ISSUE TITLE
Confusion of training

### ISSUE THREAD

**Issue by wangjuanjuan1216** [shaunyuan22/SODA-mmdetection#13]
Hello, can you tell me why val.json and test.json need to culle ignore to get val_wo_ignore.json and test_wo_ignore.json, while the original train.json does not need to cull ignore for training? Thank you very much.

**Comment by shaunyuan22** [comment]
First of all, I want to point out that only original jsons contain *ignore* annotations (namely the json files in rawData directory).

For training, we only use the splited images and jsons.  While for testing or validation, the evaluation is conducted on the original images and jsons, in which the ignore regions must be filtered to ensure that they won't affect the final performance. In other words, the ignore regions won't participate the evaluation.
