### ISSUE TITLE
An error occurred in the training evaluation

### ISSUE THREAD

**Issue by wangjuanjuan1216** [shaunyuan22/SODA-mmdetection#14]
Why is the AP value evaluated after training ten epochs all 0, and the program error is: ValueError: Cannot infer the rule for key bbox_AP, thus a specific rule must be specified.I hope you can give me a reply in your busy schedule.

**Comment by wangjuanjuan1216** [comment]
Do I need to use the sodad.py files in the sodad_eval folder here, I see that there is an evaluation item in it.

**Comment by shaunyuan22** [comment]
Whiat is your model and your test script? Is AP 0, or is the evaluation code unable to complete? I cannot provide effective assistance based on the limited information you provided. 
Moreover, these is no `sodad.py` in `sodad_eval` folder, only `sodadeval.py` in it. When you download the repository, please install it follow the instruction and use our default detaset setting during training and evaluation.

**Comment by wangjuanjuan1216** [comment]
Hello author, thank you very much for your reply, now tell you about my specific problem, I am directly downloaded the official code, after the picture preprocessing, I used the sodad-benchmarks folder under the yolox_s_70e.py configuration file, followed by running the train.py, after training 10 epochs, it will automatically conduct an evaluation, but the various ap values evaluated are 0, and the error is reported as follows: ValueError: Cannot infer the rule for key bbox_AP, thus a specific rule must be specified.
![2023-10-14 11-11-13 的屏幕截图](https://github.com/shaunyuan22/SODA-mmdetection/assets/145462494/5f941669-96b9-4c81-86ad-92a17488756d)
![2023-10-15 14-29-37 的屏幕截图](https://github.com/shaunyuan22/SODA-mmdetection/assets/145462494/e88fd416-753c-4776-97c3-95bf3b651b93)

**Comment by wangjuanjuan1216** [comment]
Can you explain what it was like to encounter this problem? How to solve it? I am a novice, thank you very much for your patience in answering my questions, which is very important for my current scientific research.

**Comment by shaunyuan22** [comment]
Any data issues should be ruled out first, I suggest to train another model such as Faster RCNN then evaluate it and see whether this error still occurs. Please let me know if there are any new developments.

**Comment by shaunyuan22** [comment]
Moreover, please provide the training logs if possible

**Comment by wangjuanjuan1216** [comment]
This is the log file of the evaluation problem when using the yolox_s model to train 20 epochs before, please take a look at where my problem is, the error problem has been mentioned in the previous question, I understand that maybe you have formulated a special evaluation rule, and some parameters of the evaluation code during training still need me to modify?
[20231013_181805.log](https://github.com/shaunyuan22/SODA-mmdetection/files/13053683/20231013_181805.log)

**Comment by shaunyuan22** [comment]
It seems there is no problem during training YOLOX from your log file, please train another model such as Faster RCNN then evaluate it and see whether this error still occurs.

**Comment by wangjuanjuan1216** [comment]
Hello author, according to the method you said to continue training several models, I chose the sparse_rcnn_r50_fpn_1x.py configuration file, and have put the required image and label path into it, but the following error appears, and the same error is reported when replaced by the faster-rcnn model. The error problem and training log are as follows, I tried to solve the error problem, but I was unsuccessful, please help me see where I need to modify, what went wrong? Did I change to another model and are there any parameter dimensions that need to be modified?[
![2023-10-23 21-13-24 的屏幕截图](https://github.com/shaunyuan22/SODA-mmdetection/assets/145462494/764114fa-b041-4c73-a25e-ba0830bb9d98)
![2023-10-23 21-13-35 的屏幕截图](https://github.com/shaunyuan22/SODA-mmdetection/assets/145462494/8ca0b9fc-cb74-4f11-9cbe-f3d9411bf412)
[20231023_210553.log](https://github.com/shaunyuan22/SODA-mmdetection/files/13071224/20231023_210553.log)
](url)

**Comment by shaunyuan22** [comment]
what went wrong when training faster rcnn?

**Comment by wangjuanjuan1216** [comment]
Hello, when training the faster-rcnn model, I encountered the same problem as above, the error problem and the training log can also be seen below, I tried to search the Internet to solve the problem, but after ruling out several possibilities, I was not able to successfully solve it. Is there some dimension inside the model in this configuration file that is wrong?
![2023-10-25 10-37-23 的屏幕截图](https://github.com/shaunyuan22/SODA-mmdetection/assets/145462494/670f1ba0-9022-4c9b-b144-0a0ee8f49e74)
![2023-10-25 10-37-38 的屏幕截图](https://github.com/shaunyuan22/SODA-mmdetection/assets/145462494/638ff8bd-ef8c-46d0-a4ee-49a19377710e)
![2023-10-25 10-37-52 的屏幕截图](https://github.com/shaunyuan22/SODA-mmdetection/assets/145462494/613279fe-c2f6-463e-8439-c6e1d824bf38)
[20231025_103334.log](https://github.com/shaunyuan22/SODA-mmdetection/files/13162969/20231025_103334.log)

**Comment by shaunyuan22** [comment]
The `featmap_strides` in `bbox_roi_extractor` should be `[4, 8, 16, 32]` instaed of `[8, 16, 32, 64]`. However, based on my experimence, this won't trigger such an error except hampering the final performance, and maybe you can debug the code to ensure whether the corresponding dimension is correct.
