### ISSUE TITLE
Dataset labeling issues

### ISSUE THREAD

**Issue by wangjuanjuan1216** [shaunyuan22/SODA-mmdetection#16]
Dear author, hello, about the production of dataset labels I would like to ask you, 1. Do you already mark the target with an area greater than 2000 pixels as ignore when you use labelimg to label the image, or after marking all the targets in 9 categories, and then change all the categories with the target box greater than 2000 to ignore through the code? 2. Are the target boxes within 1024 pixels or 2000 pixels for the 9 categories you marked?We look forward to hearing from you.

**Comment by shaunyuan22** [comment]
1. Yes, any instances who belong to 9 fore-ground categories but wtith an area larger than 2000 pixels are labeled as `ignore`
2. Yes, instances with an area smaller than 2000 pixels are labeled, but only those within 1024 pixels will be evaluated during testing.
All these details can be found in our [paper](https://ieeexplore.ieee.org/document/10168277), please refer to it.

**Comment by wangjuanjuan1216** [comment]
Hello author, the first question I think you may have misunderstood meant, I want to ask you, you are the first case when you use labelimg to label the ignore category. Or is it the second case, only 9 categories are labeled during the tagging process, and finally the category with a target box area greater than 2000 pixels is uniformly changed to ignore using the script code written by yourself?
