### ISSUE TITLE
Dataset labeling issues

### ISSUE THREAD

**Issue by wangjuanjuan1216** [shaunyuan22/SODA-mmdetection#17]
Hello author, the first question I think you may have misunderstood meant, I want to ask you, you are the first case when you use labelimg to label the ignore category. Or is it the second case, only 9 categories are labeled during the tagging process, and finally the category with a target box area greater than 2000 pixels is uniformly changed to ignore using the script code written by yourself?Since you closed the previous question, I resent the question in a new way

**Comment by shaunyuan22** [comment]
For `ignore` annotations, we have two primary solutions:
1. For the regions who belong to the predefined categories and have an area **obviously** larger than 2000 pixels or cannot be identified clearely, we assign them with `ignore` during annotating process;
2. For those instances whose areas distribute in the valuable boundary (see 1900 pixels or 2100 pixels), we first annotate them with corresponding classes, and then we use a post-process script to further assign `ignore` labels to those regions who do not not meet the area requirements.

**Comment by wangjuanjuan1216** [comment]
Thank you very much for your reply, and I would like to ask a question, when the dataset is preprocessed, the val_wo_ignore.json you want to get is obtained by the original val.json culling ignore, or the new val.json eliminated ignore after splitting. Because I see that the split json file does not contain the ignore category.

**Comment by shaunyuan22** [comment]
For example, `val_wo_ignore` is obtained by filtering `ignore` annotations from `val.json`, in which the json files are both corresponding to original images instead of split images.
