### ISSUE TITLE
Dataset usage issues

### ISSUE THREAD

**Issue by wangjuanjuan1216** [shaunyuan22/SODA-mmdetection#18]
Hello author, can this sodad dataset you made be directly used in algorithms that are not part of the MMdetection integration? For example, directly into the yolov7 or yolov8 algorithm?

**Comment by shaunyuan22** [comment]
Absolutely yes, but you need to convert the annotations to corresponding formats, like txt format for YOLO series.

**Comment by wangjuanjuan1216** [comment]
So after transferring the original labels, if I want to send a new model for training, do I also need to split the image into 800*800 patches like you, and fill the ignore area with black, so as to get the new label after preprocessing?

**Comment by shaunyuan22** [comment]
Yes
