### ISSUE TITLE
how many image after split?

### ISSUE THREAD

**Issue by zht8506** [shaunyuan22/SODA-mmdetection#20]
Thank you for your excellent work. i wonder how many image after split in soda-d? And how many image will be used during training (if mmdetection will filter the images without labels)? hope to your early reply. thank you

**Comment by shaunyuan22** [comment]
We have 58023 patch images for traing and 161579 for testing after splitting, and note that we filter empty patches during splitting the train-set, hence the number of training patches significantly less than that of testing patches.

**Comment by zht8506** [comment]
I get it, thank you for your kind and useful reply.
