### ISSUE TITLE
[Docs] 没有找到sodad_train.json这个文件

### ISSUE THREAD

**Issue by SolsticeWisp** [shaunyuan22/SODA-mmdetection#21]
### Branch

master branch  https://mmdetection.readthedocs.io/en/latest/

### 📚 The doc issue

tools\img_split\README.md中的命令python tools/img_split/sodad_split.py --cfgJson sodad_train.json使用的json文件找不到

**Comment by shaunyuan22** [comment]
Duplicate with issue #19
