### ISSUE TITLE
Why is the AP low for 'faster_rcnn_r50_fpn_1x.py'

### ISSUE THREAD

**Issue by Polarisamoon** [shaunyuan22/SODA-mmdetection#22]
Hello author, I seem to have encountered an issue while running the file "faster_rcnn_r50_fpn_1x.py". I ran it for 12 epochs, but the accuracy has remained around 0. However, when I run "retinanet_r50_fpn_1x.py", everything works fine, and the final average precision (AP) is around 29. I haven't made any changes. This is the log file. Could you please help me identify where the problem might be?
[20231104_104651.log](https://github.com/shaunyuan22/SODA-mmdetection/files/13294147/20231104_104651.log)

**Comment by Polarisamoon** [comment]
I've run both faster RNN and RetinaNet multiple times, and while the accuracy of faster RNN remains consistently low, RetinaNet runs smoothly. I noticed in[ issue 12](https://github.com/shaunyuan22/SODA-mmdetection/issues/12) that the 'faster_rcnn_r50_fpn_1x.py' exhibits ap50 to ap95 values that are extremely low, less than 5%. Would you kindly spare a moment to provide an answer amidst your busy schedule?

**Comment by shaunyuan22** [comment]
We've updated the training config for faster rcnn, because `featmap_strides` should be `[4, 8, 16, 32]` instead of `[8, 16, 32, 64]` for roi head feature extractor. Moreover, `lr=0.02` for batch size 8, it should be `0.01` for 4

**Comment by Polarisamoon** [comment]
The problem has been resolved. Thank you so much！
