### ISSUE TITLE
[Docs] sodad数据集的ori_ann_file的作用是什么？

### ISSUE THREAD

**Issue by hefangnan** [shaunyuan22/SODA-mmdetection#23]
### Branch

master branch  https://mmdetection.readthedocs.io/en/latest/

### 📚 The doc issue

在配置文件的sodad.py下的train，val，test下都有一个ori_ann_file，请问起到什么作用，和ann_file有什么区别？

**Comment by shaunyuan22** [comment]
ori_ann_file是原图的标注，ann_file是裁图之后的标注，前者主要用于evaluate
