### ISSUE TITLE
val_wo_ignore.json？

### ISSUE THREAD

**Issue by lihualilee** [shaunyuan22/SODA-mmdetection#3]
请问这个json文件是怎么生成的呢？我看tools/img_split那个里面也并没有指明

**Comment by lihualilee** [comment]
python tools/img_split/sodad_split.py --cfgJson sodad_train.json --isVis 请问这个sodad_train.json也未看到提供

**Comment by shaunyuan22** [comment]
1. 写个脚本代码遍历json文件比如val.json，然后将其中的ignroe标注直接删除，然后保存json文件即可得到val._wo_ignore.sjon;
2. sodad_train.json在tools/img_split文件夹内的split_configs中包含

**Comment by Alexwong-1024** [comment]
> 请问这个json文件是怎么生成的呢？我看tools/img_split那个里面也并没有指明

请问您生成了val._wo_ignore.sjon这个文件吗？

**Comment by 15249989527** [comment]
您好，请问将原始soda数据集的图像进行split并加入segmentation信息的原因是什么？对检测效果有什么样的好处呢
