### ISSUE TITLE
SODA_D分割后有大量空白图像

### ISSUE THREAD

**Issue by ShiZican** [shaunyuan22/SODA-mmdetection#4]
利用img_split.py分割SODA_D数据集后，很多子图像都是黑块(ignore区域)或者纯背景没有目标，请问这些图像你们在训练的时候是如何处理的？'rawData/Annotations/train.json'是分割之前的train.json嘛？'rawData/Annotations/test_wo_ignore.json'是分割之后，剔除掉ignore后的json？

**Comment by shaunyuan22** [comment]
1. 训练时可以直接跳过这些图像，测试时每一张裁剪之后的图像都需要进行测试；
2. _wo_ignore.json是对应的标注文件剔除掉ignore之后的结果

**Comment by ShiZican** [comment]
&nbsp; &nbsp; 万分感谢您的回复。在几天的摸索中我已经大致清楚了SODA数据集的使用方法，与您刚才描述的大致无差。但是在训练的时候出现了一些小问题，在此特向您请教：
&nbsp; &nbsp; 1. 请问您训练oriented rcnn的时候batchsize_per_gpu是1吗？我使用的是两张2080ti，10G显存，在训练的时候如果每张卡放1张图像，并且按您代码中描述的将800的裁剪图缩放到1200后，则会在训练几千张图像后爆显存，最后将其调整为缩放到1000才可以勉强一张卡训练一张图像。所以请您是否方便告知您当时的训练情况？
&nbsp; &nbsp; 2. 在训练时，eval的时候，会有把裁剪后的图像反向拼接再评估的操作。实际训练的时候，反向拼接耗时还行，但是后面的evaluation生成评估结果的时候会消耗很长时间，类似于程序卡住了。您当时实验的时候，soda评估也会消耗这么长时间吗？
&nbsp; &nbsp; 3. 基于2中描述的情况，我将sodaa分割后的图像标注转化为了DOTAV1的标注，最终在评估的时候没有出现上述的卡住的情况。
&nbsp; &nbsp; 4. 请问，将数据集中的空白图像进行过滤剔除与没有剔除相比是否是作弊呢？由于卡和显存不够，不删除空白图像则训练消耗时间甚久，实属无奈之举。&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shaunyuan22/SODA-mmdetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月29日(星期三) 下午4:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shaunyuan22/SODA-mmdetection] SODA_D分割后有大量空白图像 (Issue #4)





  
训练时可以直接跳过这些图像，测试时每一张裁剪之后的图像都需要进行测试；
 
_wo_ignore.json是对应的标注文件剔除掉ignore之后的结果

**Comment by shaunyuan22** [comment]
1. 在benchmark实验中，我们使用的是4张3090（24G显存），batchsize_per_gpu=1，这个我们论文5.2节介绍过。2080ti（11G显存）上我们也跑过实验，在实验设置保持一致的情况下，并没有出现如您所描述的显存爆炸的现象。
2. eval耗时较多的部分集中在计算evaluateImg这个函数，本质上是因为图像数目过于密集，所谓为了缓解这种情况我们基于COCO eval的代码写了多进程的测试代码，但还是会花不少时间，我自己测试大概在2个多小时左右。
3. 抱歉，我不太理解您说得“将sodaa分割后的图像标注转化为了DOTAV1的标注”是什么意思，因为我们的eval是在整图上进行的，或者您的意思是采用DOTAv1的测试流程进行测试会比较节省时间？希望得到您的进一步反馈，以便我们优化代码，谢谢！
4. 这个分两种情况：如果是训练时，去除空图是没有影响的，因为空图没有GT标注，事实上我们一般也会在训练中滤除空图。如果是测试，那么直接去除空图对于最终结果是有影响的，因为模型可能会在这些空图上产生虚警。
最后，顺带提一句，如果训练时一直爆显存，您可以试试将裁剪后实例分布过于密集的图像（比如子图实例数目≥1000）滤除一部分，这样可以在一定程度上避免显存爆炸的情况。希望可以帮到您~

**Comment by ShiZican** [comment]
您好，感谢回复。
1. 显存爆炸的情况是这样的：将sodaa分解为800*800的子图后，滤除了训练集上的空白图像，按照您代码sodaa_benchmark中的设置，batchsize_per_gpu=1，并且train_pipline如您代码中所设置的将图像缩放到1200*1200， sodaa数据集的version设置为“le90”，基于oriented rcnn配置文件进行了训练，在此情况下训练了大概3000张图像后，会引发“CUDA out of memory”可用内存分配不足的错误。随后，我更改了train_pipline中图像缩放的大小，缩放到1000*1000而不是1200*1200，最终能够训练，并且两张卡的内存占用在8000左右，并没有出现上述的内存爆炸的情况。&nbsp; 按您所说在2080ti上实验时没有出现显存爆炸的情况，那应该是我的代码或者config文件或者cuda driver version的问题。


2. 再次就train_with_no_ignore是将分割后的标注剔除“annotations”中的“ignore”所得到的吗？请问训练的时候这个标注参与训练了吗？还是说只在测试与每轮epoch训练结束时的eval阶段使用呢？


3. sodaa数据集的config文件中没有给version赋值， 我根据您提供的sodaa_benchmark中的config文件将version赋值为“le90”是否妥当？


4. sodaa数据集的config文件中train字典里面含有ori_ann_file一项，是否是sodaa数据集未分割之前的annotation文件的地址？ori_ann_file应该是后面的evaluation过程中，merge图像之后再评估用的吧？


5. 很抱歉，我的文字没有表述清楚。“将sodaa分割后的图像标注转化为了DOTAV1的标注”指的是，训练时，sodaa数据集的evaluation的时间耗时太久，在merge完val中的图像后，会花上非常长的时间才能得到最后的评估结果。因此我在实验中，将分割后的sodaa标注转化成了dotav1的标注形式，然后将config文件中的DatasetType更改为“DotaV1Dataset”,即相当于将sodaa数据集作为一个“自己”制作的、拥有dotav1标注形式的、只有9类的dotav1数据集，然后在测试的时候使用mmrotate提供的dotav1数据集的evaluation函数进行评估。（不知道我有没有表述清楚······）也就是您所说的，使用dotav1的测试流程会比较节省时间。


6. 冒昧地向您提出一个建议，如有冒犯请您原谅。在sodaa数据集的evaluation的过程中，不用将分割后地图像先拼接成原图，直接根据每个分割图像的标注，将每个分割后的图像作为一个单独的数据进行评估，如何？因为在小图拼接成大图的过程中，会有部分预测框重叠的问题，当然可以使用非极大值抑制来解决，但是在拼接后的大图中，可能一张图像会含有上千个实例，此时对大图来计算评估结果可能会产生过多的时间消耗。换言之，不妨像coco数据集一样，将dota数据集的评估和标注视作coco一样的基准，此后其他的数据集提出时一律按dota数据集的格式来标注新数据集，就像目前常规目标检测所做的一样。这样不同的数据集就不需要写不同的评估代码，相互比较起来也更为方便。当然，这只是我的愚见，如有冒犯，多多原谅。


7. 对于您“将实例过于密集的子图像滤除一部分”的建议，我认为对解决显存爆炸是一种可以尝试的方法，多谢您的建议。


感谢您和您的团队能够开源如此重要的研究资源，而我还因为小问题向您叨扰实在惭愧之至。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shaunyuan22/SODA-mmdetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月29日(星期三) 晚上9:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shaunyuan22/SODA-mmdetection] SODA_D分割后有大量空白图像 (Issue #4)





  
在benchmark实验中，我们使用的是4张3090（24G显存），batchsize_per_gpu=1，这个我们论文5.2节介绍过。2080ti（11G显存）上我们也跑过实验，在实验设置保持一致的情况下，并没有出现如您所描述的显存爆炸的现象。
 
eval耗时较多的部分集中在计算evaluateImg这个函数，本质上是因为图像数目过于密集，所谓为了缓解这种情况我们基于COCO eval的代码写了多进程的测试代码，但还是会花不少时间，我自己测试大概在2个多小时左右。
 
抱歉，我不太理解您说得“将sodaa分割后的图像标注转化为了DOTAV1的标注”是什么意思，因为我们的eval是在整图上进行的，或者您的意思是采用DOTAv1的测试流程进行测试会比较节省时间？希望得到您的进一步反馈，以便我们优化代码，谢谢！
 
这个分两种情况：如果是训练时，去除空图是没有影响的，因为空图没有GT标注，事实上我们一般也会在训练中滤除空图。如果是测试，那么直接去除空图对于最终结果是有影响的，因为模型可能会在这些空图上产生虚警。
 最后，顺带提一句，如果训练时一直爆显存，您可以试试将裁剪后实例分布过于密集的图像（比如子图实例数目≥1000）滤除一部分，这样可以在一定程度上避免显存爆炸的情况。希望可以帮到您~

**Comment by shaunyuan22** [comment]
1.  方便的话请邮件联系(shaunyuan@mail.nwpu.edu.cn)，我们会将使用RTX 2080Ti训练得到的log文件发给您，包括软硬件配置的详细信息，希望可以帮到您；
2. 是的。具体来说，train_wo_ignore不会对训练产生任何影响，加上这个只是为了让SODAADataset载入时不报错。测试阶段的val_wo_ignore和test_wo_ignore则是用来评估的。
3. 我们所有实验均采用le90设置，如论文5.2节中所述。
4. 是的，`_wo_ignore`这个key是为了在eval时索引到这张图对应的原图，也即评估阶段的中的merge代码部分。
5. DOTAv1只有0.5单个阈值的评估，我们的评估基于COCO实现，包含0.5-0.95多个阈值下的平均精度。因此，相比DOTAv1而言，要耗时一些。
6. 谢谢您的建议。这个我们之前也考虑过，确实如您所说，子图评估时效性更高。但是存在一个问题，因为我们在裁图时设置了一个overlap，也就是说有些目标会出现两次，甚至四次，但在评估时这些同一个目标对最终的检测指标都有贡献，这实际上不能反映出模型的真正性能。因为如果overlap区域的目标容易检测的话，那么最终的AP会被抬高，这显然不是我们想要的。所以，我们才将子图的检测结果映射回原图，然后进行评估，这实际上也是DOTA采取的评估策略。希望您可以理解
7. :)
谢谢您对我们工作的关注，以上希望可以帮到你。

**Comment by shaunyuan22** [comment]
方便的话请邮件联系(shaunyuan@mail.nwpu.edu.cn)，我们会将使用RTX 2080Ti训练得到的log文件发给您，包括软硬件配置的详细信息，希望可以帮到您；
是的。具体来说，train_wo_ignore不会对训练产生任何影响，加上这个只是为了让SODAADataset载入时不报错。测试阶段的val_wo_ignore和test_wo_ignore则是用来评估的。
我们所有实验均采用le90设置，如论文5.2节中所述。
是的，`ori_ann_file`这个key是为了在eval时索引到这张图对应的原图，也即评估阶段的中的merge代码部分。
DOTAv1只有0.5单个阈值的评估，我们的评估基于COCO实现，包含0.5-0.95多个阈值下的平均精度。因此，相比DOTAv1而言，要耗时一些。
谢谢您的建议。这个我们之前也考虑过，确实如您所说，子图评估时效性更高。但是存在一个问题，因为我们在裁图时设置了一个overlap，也就是说有些目标会出现两次，甚至四次，但在评估时这些同一个目标对最终的检测指标都有贡献，这实际上不能反映出模型的真正性能。因为如果overlap区域的目标容易检测的话，那么最终的AP会被抬高，这显然不是我们想要的。所以，我们才将子图的检测结果映射回原图，然后进行评估，这实际上也是DOTA采取的评估策略。希望您可以理解
:)
谢谢您对我们工作的关注，以上希望可以帮到你。

**Comment by shaunyuan22** [comment]
1. 方便的话请邮件联系（shaunyuan@mail.nwpu.edu.cn），我们会将使用2080Ti训练时的log文件（主要包括软硬件配置信息）发送，希望可以帮到您；
2. 完全正确。具体来说，`train_wo_ignore`不参加训练，只是为了保证数据集载入时不报错，而eval阶段需要`val_wo_ignore`或者`test_wo_ignore`完成评估；
3. 可以。我们的所有benchmark实验都基于`le90`，如我们在论文5.2提到的那样；
4. 是的。`ori_ann_file`这个key是为了在测试时索引到当前子图像对应的原图，以进行评估；
5. DOTAv1采用单阈值（0.5）进行评估，而SODAA采用COCO类型的评估，即0.5-0.95多个阈值下的AP取平均，所以相比DOTAv1的评估更加耗时；
6. 谢谢您的建议。实际上最初我们考虑过您说的这个方案，但是会存在一个问题，因为我们在裁图时设置了overlap区域以避免一个目标被切割开来，这就导致一个目标可能会出现在两张裁剪后的图像中，甚至四张。这时候直接使用子图进行评估是不太合理的，试想一下假如这些重复出现的同一个目标是容易检测的目标，那么最终的AP值就会被抬高，反之亦然。所以我们最终采用了映射回原图的评估方式，事实上这也是DOTA所采用的评估方式。希望可以理解；
7. :)

感谢您对我们工作的关注，以上希望可以帮到您~

**Comment by wap1024** [comment]
您好，对于SODA-D数据集的使用流程我存在一定的不解，我使用分割处理后的图片中带有黑块，也就是您提到的ignore类，但是您在使用说明中提到，在评估时需要使用val_wo_ignore，此时val_wo_ignore对应的图片是切割后且带黑块的igonre图片，还是切割后不带黑块的igonre图片，或者就是原图，期待您的回答，我将不胜感激。 @ShiZican @shaunyuan22
