### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Kegard** [shaunyuan22/SODA-mmdetection#7]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

~~~python
TorchVision: 0.8.2+cu110
OpenCV: 4.7.0
MMCV: 1.3.14
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.0
MMDetection: 2.18.0+unknown
~~~

### Reproduces the problem - code sample

~~~python
for data_info, result in zip(self.data_infos, dets):
            x_start, y_start = data_info['start_coord']
            new_result = []
            for i, res in enumerate(result):
                bboxes, scores = res[:, :-1], res[:, [-1]]
                bboxes = self.translate(bboxes, x_start, y_start)
                labels = np.zeros((bboxes.shape[0], 1)) + i
                new_result.append(np.concatenate(
                    [labels, bboxes, scores], axis=1
                ))
~~~

### Reproduces the problem - command or script

~~~python
 bash tools/dist_test.sh configs/singledataset/clip_end2end_freeze.py work_dirs/epoch_12_end2end_coco.pth 1 --eval bbox
~~~

### Reproduces the problem - error message

~~~python
>>> Merge detected results of patch for whole image evaluating...
Traceback (most recent call last):
  File "tools/test.py", line 238, in <module>
    main()
  File "tools/test.py", line 230, in main
    metric = dataset.evaluate(outputs, **eval_kwargs)
  File "/mmdet/datasets/sodad.py", line 506, in evaluate
    merged_results = self.merge_dets(
  File "/mmdet/datasets/sodad.py", line 426, in merge_dets
    x_start, y_start = data_info['start_coord']
KeyError: 'start_coord'
~~~

### Additional information

I have download the SODA-D dataset and split the dataset,but I don't found the "start_coord" in any json file. If there is something wrong with the Annotations in the dataset, can u upload the correct Annotation? or tell me how to solve it with code?

**Comment by shaunyuan22** [comment]
The annotations are correct. It seems that there are some issues during the split process.

If the image splitting process is running properly, you will eventually obtain a JSON file that stores the sub-image's image information and annotation information. In this JSON file, the keyword "start_coord" represents the coordinates of the top-left corner of the current sub-image in relation to the original image. 

We recommend that you check the annotation file generated by the cropping process. Please note that during testing, you will need the JSON file that saves the cropping information (divData/Annotations/test.json) and the annotation file that saves the information of the original image (rawData/Annotations/test_wo_ignore.json).
