### ISSUE TITLE
Dataset issues

### ISSUE THREAD

**Issue by wangjuanjuan1216** [shaunyuan22/SODA-mmdetection#9]
I would like to ask if you have already registered the SODADDateset dataset with the dataset registry using decorators or registration functions in the given code. I hope you will take the time out of your busy schedule to answer my doubts, thank you very much, it is very important for my current graduate studies.

**Comment by shaunyuan22** [comment]
yes, see the line 24 of [sodad.py](https://github.com/shaunyuan22/SODA-mmdetection/blob/master/mmdet/datasets/sodad.py) and line 18 of [__init__.py](https://github.com/shaunyuan22/SODA-mmdetection/blob/master/mmdet/datasets/__init__.py)

**Comment by wangjuanjuan1216** [comment]
Traceback (most recent call last):
  File "D:\xiazai\SODA-mmdetection-master\tools\train.py", line 249, in <module>
    main()
  File "D:\xiazai\SODA-mmdetection-master\tools\train.py", line 223, in main
    datasets = [build_dataset(cfg.data.train)]
  File "d:\xiazai\mmdetection-master\mmdetection-master\mmdet\datasets\builder.py", line 79, in build_dataset
    cp_cfg['dataset'] = build_dataset(cp_cfg['dataset'])
  File "d:\xiazai\mmdetection-master\mmdetection-master\mmdet\datasets\builder.py", line 85, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "C:\Users\wangzihan\.conda\envs\mmdet\lib\site-packages\mmcv\utils\registry.py", line 61, in build_from_cfg
    raise KeyError(
KeyError: 'SODADDataset is not in the dataset registry'
Why have I made sure that sodaddataset is imported, and the above problems still occur, can you help me take a look?please help me,thank you very much

**Comment by wangjuanjuan1216** [comment]
How do I get the rawData/Annotations/val_wo_ignore.json file in the config file? From the tag file under the official website, there is only the original train.json val.json test.json。I hope you can write back to me in your busy schedule, thank you very much。
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Sat, Oct 7, 2023 10:57 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [shaunyuan22/SODA-mmdetection] Dataset issues (Issue #9)

&nbsp;



 
yes, see the line 18 of init.py
